services:
  - type: web
    name: coindcx-trade-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python swing_trade_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
